version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'app'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3308:3308"
    environment:
      MYSQL_DATABASE: 'facturacion'
      MYSQL_ALLOW_EMPTY_PASSWORD: 
      MYSQL_ROOT_PASSWORD: "andi1994sol"
    volumes:
      - ./db:/var/lib/mysql